//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPortal.Models.dbEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalEntities : DbContext
    {
        public PortalEntities()
            : base("name=PortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<AlbumStyle> AlbumStyle { get; set; }
        public virtual DbSet<Composition> Composition { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<MusicalGroup> MusicalGroup { get; set; }
        public virtual DbSet<MusicalGroupType> MusicalGroupType { get; set; }
        public virtual DbSet<Musician> Musician { get; set; }
        public virtual DbSet<MusiciansInGroup> MusiciansInGroup { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserDownloadedCompositions> UserDownloadedCompositions { get; set; }
        public virtual DbSet<UserFavoriteComposition> UserFavoriteComposition { get; set; }
        public virtual DbSet<UserFavoriteMusicalGroup> UserFavoriteMusicalGroup { get; set; }
        public virtual DbSet<UserListenedComposition> UserListenedComposition { get; set; }
    }
}
