//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPortal.Models.dbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFavoriteComposition
    {
        public int user_id { get; set; }
        public int composition_id { get; set; }
        public Nullable<System.DateTime> likeDate { get; set; }
    
        public virtual Composition Composition { get; set; }
        public virtual User User { get; set; }
    }
}
